using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using RealEstate.Shared.Models.Entities.Clients;

namespace RealEstate.Shared.Data.Context
{
    public class IdentityUsersDBContext : DbContext //IdentityDbContext<ApplicationUser>
    {
        public IdentityUsersDBContext(DbContextOptions<IdentityUsersDBContext> options)
            : base(options) { }

        //public DbSet<ApplicationUser> ApplicationUsers { get; set; }

        // The Identity Tables will be AutoGenerated here:
        /*
        User            Represents the user.
        Role            Represents a role.
        UserClaim       Represents a claim that a user possesses.
        UserToken       Represents an authentication token for a user.
        UserLogin       Associates a user with a login.
        RoleClaim       Represents a claim that's granted to all users within a role.
        UserRole        A join entity that associates users and roles.
        */

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {

            if (!optionsBuilder.IsConfigured)
            {
                optionsBuilder
                    .UseNpgsql("Host=127.0.0.1;Database=IdentityUsers;Username=postgres;Password=admin");
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Contact>().HasIndex(c => c.Id).IsUnique();

            modelBuilder.Entity<Contact>()
                .HasOne(c => c.Client)
                .WithOne(cl => cl.Contact)
                .HasForeignKey<Contact>(c => c.ApplicationUserId);


            base.OnModelCreating(modelBuilder);
            // This is required as it initializes Identity
        }
    }
}