name: api.listings

on:
  workflow_dispatch:
  push:
    branches:
    - main

    paths:
    - Microservices/ListingsMicroservice**
    - .github/workflows/api.listings.yml
  
  pull_request:
    branches:
    - main

    paths:
    - Microservices/ListingsMicroservice**
    - .github/workflows/api.listings.yml

env:
  SERVICE: api.listings
  IMAGE: api.listings

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Restore dependencies
      run: dotnet restore Microservices/ListingsMicroservice/ListingsMicroservice.csproj

    - name: Build
      run: dotnet build Microservices/ListingsMicroservice/ListingsMicroservice.csproj --no-restore
