name: api.contracts

on:
  workflow_dispatch:
  push:
    branches:
    - main

    paths:
    - Microservices/ContractsMicroservice**
    - .github/workflows/api.contracts.yml
  
  pull_request:
    branches:
    - main

    paths:
    - Microservices/ContractsMicroservice**
    - .github/workflows/api.contracts.yml

env:
  SERVICE: api.contracts
  IMAGE: api.contracts

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Restore dependencies
      run: dotnet restore Microservices/ContractsMicroservice/ContractsMicroservice.csproj

    - name: Build
      run: dotnet build Microservices/ContractsMicroservice/ContractsMicroservice.csproj --no-restore
