name: api.clients

on:
  workflow_dispatch:
  push:
    branches:
    - main

    paths:
    - Microservices/ClientsMicroservice**
    - .github/workflows/api.clients.yml
  
  pull_request:
    branches:
    - main

    paths:
    - Microservices/ClientsMicroservice**
    - .github/workflows/api.clients.yml

env:
  SERVICE: api.clients
  IMAGE: api.clients

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 7.0.x

    - name: Restore dependencies
      run: dotnet restore Microservices/ClientsMicroservice/ClientsMicroservice.csproj

    - name: Build
      run: dotnet build Microservices/ClientsMicroservice/ClientsMicroservice.csproj --no-restore
