name: api.estates

on:
  workflow_dispatch:
  push:
    branches:
    - main

    paths:
    - Microservices/EstatesMicroservice**
    - .github/workflows/api.estates.yml
  
  pull_request:
    branches:
    - main

    paths:
    - Microservices/EstatesMicroservice**
    - .github/workflows/api.estates.yml

env:
  SERVICE: api.estates
  IMAGE: api.estates

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Restore dependencies
      run: dotnet restore Microservices/EstatesMicroservice/EstatesMicroservice.csproj

    - name: Build
      run: dotnet build Microservices/EstatesMicroservice/EstatesMicroservice.csproj --no-restore
